/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5ff27626-edcf-45d1-810d-c4f5ea769085",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qaw1pSYW5",
    "aws_user_pools_web_client_id": "4cke1p3dpmd1fdnp6ef58q2air",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://irotyz3aynai5gohvemmp3bqdy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "aws-athena-query-results-devtest",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
